/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Factory__factory>
getContractFactory(name: 'InterestRateModel', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InterestRateModel__factory>
getContractFactory(name: 'LendingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LendingPool__factory>
getContractFactory(name: 'LiquidationEngine', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LiquidationEngine__factory>
getContractFactory(name: 'OracleHub', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OracleHub__factory>
getContractFactory(name: 'IFlashSwapReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFlashSwapReceiver__factory>
getContractFactory(name: 'Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pair__factory>
getContractFactory(name: 'PoolStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolStorage__factory>
getContractFactory(name: 'RiskEngine', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RiskEngine__factory>
getContractFactory(name: 'Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Router__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>

  getContractAt(name: 'Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Factory>
getContractAt(name: 'InterestRateModel', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InterestRateModel>
getContractAt(name: 'LendingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LendingPool>
getContractAt(name: 'LiquidationEngine', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LiquidationEngine>
getContractAt(name: 'OracleHub', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OracleHub>
getContractAt(name: 'IFlashSwapReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFlashSwapReceiver>
getContractAt(name: 'Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pair>
getContractAt(name: 'PoolStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolStorage>
getContractAt(name: 'RiskEngine', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RiskEngine>
getContractAt(name: 'Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Router>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>

  deployContract(name: 'Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Factory>
deployContract(name: 'InterestRateModel', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InterestRateModel>
deployContract(name: 'LendingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPool>
deployContract(name: 'LiquidationEngine', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LiquidationEngine>
deployContract(name: 'OracleHub', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleHub>
deployContract(name: 'IFlashSwapReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashSwapReceiver>
deployContract(name: 'Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pair>
deployContract(name: 'PoolStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolStorage>
deployContract(name: 'RiskEngine', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RiskEngine>
deployContract(name: 'Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>

  deployContract(name: 'Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Factory>
deployContract(name: 'InterestRateModel', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InterestRateModel>
deployContract(name: 'LendingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPool>
deployContract(name: 'LiquidationEngine', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LiquidationEngine>
deployContract(name: 'OracleHub', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleHub>
deployContract(name: 'IFlashSwapReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashSwapReceiver>
deployContract(name: 'Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pair>
deployContract(name: 'PoolStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolStorage>
deployContract(name: 'RiskEngine', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RiskEngine>
deployContract(name: 'Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  