/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface InterestRateModelInterface extends Interface {
    getFunction(nameOrSignature: "baseRate" | "getBorrowRate" | "getBorrowRatePerSecond" | "getSupplyRate" | "getUtilizationRate" | "jumpMultiplierPerSecond" | "kink" | "kinkHigh" | "kinkLow" | "multiplierPerSecond"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'baseRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBorrowRate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBorrowRatePerSecond', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSupplyRate', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUtilizationRate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'jumpMultiplierPerSecond', values?: undefined): string;
encodeFunctionData(functionFragment: 'kink', values?: undefined): string;
encodeFunctionData(functionFragment: 'kinkHigh', values?: undefined): string;
encodeFunctionData(functionFragment: 'kinkLow', values?: undefined): string;
encodeFunctionData(functionFragment: 'multiplierPerSecond', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'baseRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowRatePerSecond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSupplyRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUtilizationRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jumpMultiplierPerSecond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kink', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kinkHigh', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kinkLow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiplierPerSecond', data: BytesLike): Result;
  }

  

  export interface InterestRateModel extends BaseContract {
    
    connect(runner?: ContractRunner | null): InterestRateModel;
    waitForDeployment(): Promise<this>;

    interface: InterestRateModelInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    baseRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBorrowRate: TypedContractMethod<
      [totalDebt: BigNumberish, totalLiquidity: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getBorrowRatePerSecond: TypedContractMethod<
      [cash: BigNumberish, borrows: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSupplyRate: TypedContractMethod<
      [totalDebt: BigNumberish, totalLiquidity: BigNumberish, reserveFactor: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getUtilizationRate: TypedContractMethod<
      [cash: BigNumberish, borrows: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    jumpMultiplierPerSecond: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kink: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kinkHigh: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kinkLow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    multiplierPerSecond: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'baseRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowRate'): TypedContractMethod<
      [totalDebt: BigNumberish, totalLiquidity: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowRatePerSecond'): TypedContractMethod<
      [cash: BigNumberish, borrows: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSupplyRate'): TypedContractMethod<
      [totalDebt: BigNumberish, totalLiquidity: BigNumberish, reserveFactor: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUtilizationRate'): TypedContractMethod<
      [cash: BigNumberish, borrows: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jumpMultiplierPerSecond'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kink'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kinkHigh'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kinkLow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'multiplierPerSecond'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }