/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface LiquidationEngineInterface extends Interface {
    getFunction(nameOrSignature: "getMaxLiquidatableDebt" | "lendingPool" | "liquidate" | "oracle" | "poolStorage" | "riskEngine"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Liquidation"): EventFragment;

    encodeFunctionData(functionFragment: 'getMaxLiquidatableDebt', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lendingPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidate', values: [AddressLike, AddressLike, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolStorage', values?: undefined): string;
encodeFunctionData(functionFragment: 'riskEngine', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getMaxLiquidatableDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lendingPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'riskEngine', data: BytesLike): Result;
  }

  
    export namespace LiquidationEvent {
      export type InputTuple = [liquidator: AddressLike, borrower: AddressLike, debtAsset: AddressLike, collateralAsset: AddressLike, debtCovered: BigNumberish, collateralSeized: BigNumberish, bonus: BigNumberish];
      export type OutputTuple = [liquidator: string, borrower: string, debtAsset: string, collateralAsset: string, debtCovered: bigint, collateralSeized: bigint, bonus: bigint];
      export interface OutputObject {liquidator: string, borrower: string, debtAsset: string, collateralAsset: string, debtCovered: bigint, collateralSeized: bigint, bonus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LiquidationEngine extends BaseContract {
    
    connect(runner?: ContractRunner | null): LiquidationEngine;
    waitForDeployment(): Promise<this>;

    interface: LiquidationEngineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMaxLiquidatableDebt: TypedContractMethod<
      [borrower: AddressLike, debtAsset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lendingPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    liquidate: TypedContractMethod<
      [borrower: AddressLike, debtAsset: AddressLike, collateralAsset: AddressLike, debtToCover: BigNumberish, receiveUnderlying: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolStorage: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    riskEngine: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMaxLiquidatableDebt'): TypedContractMethod<
      [borrower: AddressLike, debtAsset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lendingPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidate'): TypedContractMethod<
      [borrower: AddressLike, debtAsset: AddressLike, collateralAsset: AddressLike, debtToCover: BigNumberish, receiveUnderlying: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolStorage'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'riskEngine'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Liquidation'): TypedContractEvent<LiquidationEvent.InputTuple, LiquidationEvent.OutputTuple, LiquidationEvent.OutputObject>;

    filters: {
      
      'Liquidation(address,address,address,address,uint256,uint256,uint256)': TypedContractEvent<LiquidationEvent.InputTuple, LiquidationEvent.OutputTuple, LiquidationEvent.OutputObject>;
      Liquidation: TypedContractEvent<LiquidationEvent.InputTuple, LiquidationEvent.OutputTuple, LiquidationEvent.OutputObject>;
    
    };
  }