/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PoolStorage {
      
    export type AssetStateStruct = {supplyIndex: BigNumberish, borrowIndex: BigNumberish, totalSupplyShares: BigNumberish, totalDebtShares: BigNumberish, lastAccrualTimestamp: BigNumberish, initialized: boolean}

    export type AssetStateStructOutput = [supplyIndex: bigint, borrowIndex: bigint, totalSupplyShares: bigint, totalDebtShares: bigint, lastAccrualTimestamp: bigint, initialized: boolean] & {supplyIndex: bigint, borrowIndex: bigint, totalSupplyShares: bigint, totalDebtShares: bigint, lastAccrualTimestamp: bigint, initialized: boolean }
  
    }

  export interface PoolStorageInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "GOVERNOR_ROLE" | "LIQUIDATOR_ROLE" | "POOL_ROLE" | "addUserDebt" | "addUserSupply" | "amountToShares" | "getRoleAdmin" | "getState" | "getStateView" | "getUserDebtShares" | "getUserPosition" | "getUserSupplyShares" | "grantLiquidatorRole" | "grantPoolRole" | "grantRole" | "hasRole" | "isKnownUser" | "isRegistered" | "knownUsers" | "knownUsersLength" | "registerAsset" | "registeredAssets" | "registeredAssetsLength" | "removeUserDebt" | "removeUserSupply" | "renounceRole" | "revokeRole" | "setIndexes" | "sharesToAmount" | "supportsInterface" | "totalDebtAmount" | "totalSupplyAmount" | "utilizationRate" | "writeOffDebt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetRegistered" | "DebtAdded" | "DebtRemoved" | "DebtWrittenOff" | "IndexUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SupplyAdded" | "SupplyRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOVERNOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'POOL_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addUserDebt', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'addUserSupply', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'amountToShares', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getState', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStateView', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserDebtShares', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserPosition', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserSupplyShares', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'grantLiquidatorRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantPoolRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isKnownUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'knownUsers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'knownUsersLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAsset', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registeredAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registeredAssetsLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeUserDebt', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeUserSupply', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setIndexes', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'sharesToAmount', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalDebtAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalSupplyAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'utilizationRate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'writeOffDebt', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOVERNOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'POOL_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addUserDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addUserSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'amountToShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStateView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserDebtShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserSupplyShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantLiquidatorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantPoolRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKnownUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'knownUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'knownUsersLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredAssetsLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeUserDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeUserSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setIndexes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sharesToAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDebtAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupplyAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'utilizationRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'writeOffDebt', data: BytesLike): Result;
  }

  
    export namespace AssetRegisteredEvent {
      export type InputTuple = [asset: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [asset: string, timestamp: bigint];
      export interface OutputObject {asset: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DebtAddedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, shares: BigNumberish];
      export type OutputTuple = [user: string, asset: string, shares: bigint];
      export interface OutputObject {user: string, asset: string, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DebtRemovedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, shares: BigNumberish];
      export type OutputTuple = [user: string, asset: string, shares: bigint];
      export interface OutputObject {user: string, asset: string, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DebtWrittenOffEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, asset: string, amount: bigint];
      export interface OutputObject {user: string, asset: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IndexUpdatedEvent {
      export type InputTuple = [asset: AddressLike, supplyIndex: BigNumberish, borrowIndex: BigNumberish];
      export type OutputTuple = [asset: string, supplyIndex: bigint, borrowIndex: bigint];
      export interface OutputObject {asset: string, supplyIndex: bigint, borrowIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplyAddedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, shares: BigNumberish];
      export type OutputTuple = [user: string, asset: string, shares: bigint];
      export interface OutputObject {user: string, asset: string, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplyRemovedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, shares: BigNumberish];
      export type OutputTuple = [user: string, asset: string, shares: bigint];
      export interface OutputObject {user: string, asset: string, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PoolStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): PoolStorage;
    waitForDeployment(): Promise<this>;

    interface: PoolStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GOVERNOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LIQUIDATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    POOL_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addUserDebt: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addUserSupply: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    amountToShares: TypedContractMethod<
      [amount: BigNumberish, index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getState: TypedContractMethod<
      [asset: AddressLike, ],
      [PoolStorage.AssetStateStructOutput],
      'view'
    >
    

    
    getStateView: TypedContractMethod<
      [asset: AddressLike, ],
      [PoolStorage.AssetStateStructOutput],
      'view'
    >
    

    
    getUserDebtShares: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserPosition: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [[bigint, bigint] & {supplyShares: bigint, debtShares: bigint }],
      'view'
    >
    

    
    getUserSupplyShares: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantLiquidatorRole: TypedContractMethod<
      [liquidator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantPoolRole: TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isKnownUser: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    knownUsers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    knownUsersLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerAsset: TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registeredAssets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registeredAssetsLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    removeUserDebt: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeUserSupply: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setIndexes: TypedContractMethod<
      [asset: AddressLike, newSupplyIndex: BigNumberish, newBorrowIndex: BigNumberish, newTimestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sharesToAmount: TypedContractMethod<
      [shares: BigNumberish, index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalDebtAmount: TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalSupplyAmount: TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    utilizationRate: TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    writeOffDebt: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, arg2: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GOVERNOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'POOL_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addUserDebt'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addUserSupply'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'amountToShares'): TypedContractMethod<
      [amount: BigNumberish, index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getState'): TypedContractMethod<
      [asset: AddressLike, ],
      [PoolStorage.AssetStateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStateView'): TypedContractMethod<
      [asset: AddressLike, ],
      [PoolStorage.AssetStateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserDebtShares'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserPosition'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [[bigint, bigint] & {supplyShares: bigint, debtShares: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserSupplyShares'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantLiquidatorRole'): TypedContractMethod<
      [liquidator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantPoolRole'): TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isKnownUser'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'knownUsers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'knownUsersLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerAsset'): TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registeredAssets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registeredAssetsLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeUserDebt'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeUserSupply'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setIndexes'): TypedContractMethod<
      [asset: AddressLike, newSupplyIndex: BigNumberish, newBorrowIndex: BigNumberish, newTimestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sharesToAmount'): TypedContractMethod<
      [shares: BigNumberish, index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalDebtAmount'): TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupplyAmount'): TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'utilizationRate'): TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'writeOffDebt'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, arg2: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AssetRegistered'): TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
getEvent(key: 'DebtAdded'): TypedContractEvent<DebtAddedEvent.InputTuple, DebtAddedEvent.OutputTuple, DebtAddedEvent.OutputObject>;
getEvent(key: 'DebtRemoved'): TypedContractEvent<DebtRemovedEvent.InputTuple, DebtRemovedEvent.OutputTuple, DebtRemovedEvent.OutputObject>;
getEvent(key: 'DebtWrittenOff'): TypedContractEvent<DebtWrittenOffEvent.InputTuple, DebtWrittenOffEvent.OutputTuple, DebtWrittenOffEvent.OutputObject>;
getEvent(key: 'IndexUpdated'): TypedContractEvent<IndexUpdatedEvent.InputTuple, IndexUpdatedEvent.OutputTuple, IndexUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SupplyAdded'): TypedContractEvent<SupplyAddedEvent.InputTuple, SupplyAddedEvent.OutputTuple, SupplyAddedEvent.OutputObject>;
getEvent(key: 'SupplyRemoved'): TypedContractEvent<SupplyRemovedEvent.InputTuple, SupplyRemovedEvent.OutputTuple, SupplyRemovedEvent.OutputObject>;

    filters: {
      
      'AssetRegistered(address,uint256)': TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
      AssetRegistered: TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
    

      'DebtAdded(address,address,uint128)': TypedContractEvent<DebtAddedEvent.InputTuple, DebtAddedEvent.OutputTuple, DebtAddedEvent.OutputObject>;
      DebtAdded: TypedContractEvent<DebtAddedEvent.InputTuple, DebtAddedEvent.OutputTuple, DebtAddedEvent.OutputObject>;
    

      'DebtRemoved(address,address,uint128)': TypedContractEvent<DebtRemovedEvent.InputTuple, DebtRemovedEvent.OutputTuple, DebtRemovedEvent.OutputObject>;
      DebtRemoved: TypedContractEvent<DebtRemovedEvent.InputTuple, DebtRemovedEvent.OutputTuple, DebtRemovedEvent.OutputObject>;
    

      'DebtWrittenOff(address,address,uint256)': TypedContractEvent<DebtWrittenOffEvent.InputTuple, DebtWrittenOffEvent.OutputTuple, DebtWrittenOffEvent.OutputObject>;
      DebtWrittenOff: TypedContractEvent<DebtWrittenOffEvent.InputTuple, DebtWrittenOffEvent.OutputTuple, DebtWrittenOffEvent.OutputObject>;
    

      'IndexUpdated(address,uint128,uint128)': TypedContractEvent<IndexUpdatedEvent.InputTuple, IndexUpdatedEvent.OutputTuple, IndexUpdatedEvent.OutputObject>;
      IndexUpdated: TypedContractEvent<IndexUpdatedEvent.InputTuple, IndexUpdatedEvent.OutputTuple, IndexUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SupplyAdded(address,address,uint128)': TypedContractEvent<SupplyAddedEvent.InputTuple, SupplyAddedEvent.OutputTuple, SupplyAddedEvent.OutputObject>;
      SupplyAdded: TypedContractEvent<SupplyAddedEvent.InputTuple, SupplyAddedEvent.OutputTuple, SupplyAddedEvent.OutputObject>;
    

      'SupplyRemoved(address,address,uint128)': TypedContractEvent<SupplyRemovedEvent.InputTuple, SupplyRemovedEvent.OutputTuple, SupplyRemovedEvent.OutputObject>;
      SupplyRemoved: TypedContractEvent<SupplyRemovedEvent.InputTuple, SupplyRemovedEvent.OutputTuple, SupplyRemovedEvent.OutputObject>;
    
    };
  }