/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RouterInterface extends Interface {
    getFunction(nameOrSignature: "factory" | "oracle" | "quoteExactInput" | "quoteExactOutput" | "swapExactTokensForTokens" | "swapTokensForExactTokens"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteExactInput', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'quoteExactOutput', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'swapExactTokensForTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapTokensForExactTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteExactInput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteExactOutput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTokensForExactTokens', data: BytesLike): Result;
  }

  

  export interface Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): Router;
    waitForDeployment(): Promise<this>;

    interface: RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteExactInput: TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >
    

    
    quoteExactOutput: TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >
    

    
    swapExactTokensForTokens: TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    swapTokensForExactTokens: TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteExactInput'): TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'quoteExactOutput'): TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'swapExactTokensForTokens'): TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapTokensForExactTokens'): TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }