/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFlashSwapReceiver, IFlashSwapReceiverInterface } from "../../Pair.sol/IFlashSwapReceiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount0",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amount1",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "flashSwapCallback",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFlashSwapReceiver__factory {
    static readonly abi = _abi;
    static createInterface(): IFlashSwapReceiverInterface {
      return new Interface(_abi) as IFlashSwapReceiverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFlashSwapReceiver {
      return new Contract(address, _abi, runner) as unknown as IFlashSwapReceiver;
    }
  }
  