/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PairInterface extends Interface {
    getFunction(nameOrSignature: "FEE_DENOMINATOR" | "MINIMUM_LIQUIDITY" | "allowance" | "approve" | "balanceOf" | "baseFee" | "burn" | "circuitBreakerTripped" | "decimals" | "decreaseAllowance" | "factory" | "feeTo" | "getReserves" | "increaseAllowance" | "increaseObservationCardinality" | "mint" | "name" | "observationCardinality" | "observationCardinalityNext" | "observationIndex" | "observations" | "observe" | "price0CumulativeLast" | "price1CumulativeLast" | "protocolFeeBps" | "resetCircuitBreaker" | "setFee" | "swap" | "symbol" | "token0" | "token1" | "totalSupply" | "transfer" | "transferFrom" | "volatilityFee"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "Burn" | "CircuitBreakerReset" | "CircuitBreakerTripped" | "FeeUpdated" | "Mint" | "Swap" | "Sync" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINIMUM_LIQUIDITY', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'baseFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'burn', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'circuitBreakerTripped', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'decreaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeTo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'increaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'increaseObservationCardinality', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'observationCardinality', values?: undefined): string;
encodeFunctionData(functionFragment: 'observationCardinalityNext', values?: undefined): string;
encodeFunctionData(functionFragment: 'observationIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'observations', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'observe', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'price0CumulativeLast', values?: undefined): string;
encodeFunctionData(functionFragment: 'price1CumulativeLast', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'resetCircuitBreaker', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFee', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swap', values: [BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'token0', values?: undefined): string;
encodeFunctionData(functionFragment: 'token1', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'volatilityFee', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'FEE_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINIMUM_LIQUIDITY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'circuitBreakerTripped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decreaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseObservationCardinality', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observationCardinality', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observationCardinalityNext', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observationIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observe', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'price0CumulativeLast', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'price1CumulativeLast', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetCircuitBreaker', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'volatilityFee', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnEvent {
      export type InputTuple = [sender: AddressLike, amount0: BigNumberish, amount1: BigNumberish, to: AddressLike];
      export type OutputTuple = [sender: string, amount0: bigint, amount1: bigint, to: string];
      export interface OutputObject {sender: string, amount0: bigint, amount1: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CircuitBreakerResetEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CircuitBreakerTrippedEvent {
      export type InputTuple = [priceMove: BigNumberish, threshold: BigNumberish];
      export type OutputTuple = [priceMove: bigint, threshold: bigint];
      export interface OutputObject {priceMove: bigint, threshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeUpdatedEvent {
      export type InputTuple = [baseFee: BigNumberish, volatilityFee: BigNumberish];
      export type OutputTuple = [baseFee: bigint, volatilityFee: bigint];
      export interface OutputObject {baseFee: bigint, volatilityFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintEvent {
      export type InputTuple = [sender: AddressLike, amount0: BigNumberish, amount1: BigNumberish];
      export type OutputTuple = [sender: string, amount0: bigint, amount1: bigint];
      export interface OutputObject {sender: string, amount0: bigint, amount1: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapEvent {
      export type InputTuple = [sender: AddressLike, amount0In: BigNumberish, amount1In: BigNumberish, amount0Out: BigNumberish, amount1Out: BigNumberish, to: AddressLike];
      export type OutputTuple = [sender: string, amount0In: bigint, amount1In: bigint, amount0Out: bigint, amount1Out: bigint, to: string];
      export interface OutputObject {sender: string, amount0In: bigint, amount1In: bigint, amount0Out: bigint, amount1Out: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SyncEvent {
      export type InputTuple = [reserve0: BigNumberish, reserve1: BigNumberish];
      export type OutputTuple = [reserve0: bigint, reserve1: bigint];
      export interface OutputObject {reserve0: bigint, reserve1: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Pair extends BaseContract {
    
    connect(runner?: ContractRunner | null): Pair;
    waitForDeployment(): Promise<this>;

    interface: PairInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MINIMUM_LIQUIDITY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    baseFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    burn: TypedContractMethod<
      [to: AddressLike, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'nonpayable'
    >
    

    
    circuitBreakerTripped: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decreaseAllowance: TypedContractMethod<
      [spender: AddressLike, subtractedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    feeTo: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {reserve0_: bigint, reserve1_: bigint, blockTimestampLast_: bigint }],
      'view'
    >
    

    
    increaseAllowance: TypedContractMethod<
      [spender: AddressLike, addedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    increaseObservationCardinality: TypedContractMethod<
      [next: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    observationCardinality: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    observationCardinalityNext: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    observationIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    observations: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint] & {timestamp: bigint, price0Cumulative: bigint, price1Cumulative: bigint }],
      'view'
    >
    

    
    observe: TypedContractMethod<
      [secondsAgo: BigNumberish, ],
      [[bigint, bigint] & {price0Avg: bigint, price1Avg: bigint }],
      'view'
    >
    

    
    price0CumulativeLast: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    price1CumulativeLast: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    protocolFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    resetCircuitBreaker: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setFee: TypedContractMethod<
      [_baseFee: BigNumberish, _volatilityFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swap: TypedContractMethod<
      [amount0Out: BigNumberish, amount1Out: BigNumberish, to: AddressLike, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token0: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token1: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    volatilityFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MINIMUM_LIQUIDITY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'baseFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [to: AddressLike, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'circuitBreakerTripped'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decreaseAllowance'): TypedContractMethod<
      [spender: AddressLike, subtractedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'feeTo'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {reserve0_: bigint, reserve1_: bigint, blockTimestampLast_: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'increaseAllowance'): TypedContractMethod<
      [spender: AddressLike, addedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'increaseObservationCardinality'): TypedContractMethod<
      [next: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'observationCardinality'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'observationCardinalityNext'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'observationIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'observations'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint] & {timestamp: bigint, price0Cumulative: bigint, price1Cumulative: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'observe'): TypedContractMethod<
      [secondsAgo: BigNumberish, ],
      [[bigint, bigint] & {price0Avg: bigint, price1Avg: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'price0CumulativeLast'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'price1CumulativeLast'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'resetCircuitBreaker'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFee'): TypedContractMethod<
      [_baseFee: BigNumberish, _volatilityFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [amount0Out: BigNumberish, amount1Out: BigNumberish, to: AddressLike, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token0'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token1'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'volatilityFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Burn'): TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
getEvent(key: 'CircuitBreakerReset'): TypedContractEvent<CircuitBreakerResetEvent.InputTuple, CircuitBreakerResetEvent.OutputTuple, CircuitBreakerResetEvent.OutputObject>;
getEvent(key: 'CircuitBreakerTripped'): TypedContractEvent<CircuitBreakerTrippedEvent.InputTuple, CircuitBreakerTrippedEvent.OutputTuple, CircuitBreakerTrippedEvent.OutputObject>;
getEvent(key: 'FeeUpdated'): TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
getEvent(key: 'Mint'): TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
getEvent(key: 'Swap'): TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
getEvent(key: 'Sync'): TypedContractEvent<SyncEvent.InputTuple, SyncEvent.OutputTuple, SyncEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Burn(address,uint256,uint256,address)': TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
      Burn: TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
    

      'CircuitBreakerReset(address)': TypedContractEvent<CircuitBreakerResetEvent.InputTuple, CircuitBreakerResetEvent.OutputTuple, CircuitBreakerResetEvent.OutputObject>;
      CircuitBreakerReset: TypedContractEvent<CircuitBreakerResetEvent.InputTuple, CircuitBreakerResetEvent.OutputTuple, CircuitBreakerResetEvent.OutputObject>;
    

      'CircuitBreakerTripped(uint256,uint256)': TypedContractEvent<CircuitBreakerTrippedEvent.InputTuple, CircuitBreakerTrippedEvent.OutputTuple, CircuitBreakerTrippedEvent.OutputObject>;
      CircuitBreakerTripped: TypedContractEvent<CircuitBreakerTrippedEvent.InputTuple, CircuitBreakerTrippedEvent.OutputTuple, CircuitBreakerTrippedEvent.OutputObject>;
    

      'FeeUpdated(uint16,uint16)': TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
      FeeUpdated: TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
    

      'Mint(address,uint256,uint256)': TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
      Mint: TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
    

      'Swap(address,uint256,uint256,uint256,uint256,address)': TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
      Swap: TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
    

      'Sync(uint112,uint112)': TypedContractEvent<SyncEvent.InputTuple, SyncEvent.OutputTuple, SyncEvent.OutputObject>;
      Sync: TypedContractEvent<SyncEvent.InputTuple, SyncEvent.OutputTuple, SyncEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }