@ApiService_HostAddress = http://localhost:5492

GET {{ApiService_HostAddress}}/api/pools
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/pools/{{pairAddress}}
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/swap/quote?amountIn=1000000000000000000&path=0xTokenA&path=0xTokenB
Accept: application/json

###
